-- ============================================================================
-- VERSIX NORMA - CONTINUAÇÃO: 210 FAQs (91-300)
-- ============================================================================
-- Este arquivo complementa o versix_norma_faqs_v2.sql
-- Execute APÓS o arquivo principal
-- ============================================================================

-- ============================================================================
-- CATEGORIA 4: ANIMAIS - PASSEIO (20 FAQs: 91-110)
-- ============================================================================

INSERT INTO public.faqs (question, answer, category, tags, keywords, article_reference, scenario_type, tone, priority, question_variations, condominio_id) VALUES

-- Pergunta 91
('Meu cachorro precisa usar coleira?',
'Sim, SEMPRE. Coleira, focinheira (se necessário) e saquinhos para recolher fezes são OBRIGATÓRIOS. Não há horário específico, mas siga as regras.',
'animais_passeio',
ARRAY['coleira', 'obrigacao', 'regras'],
ARRAY['coleira', 'guia', 'obrigatorio', 'lei', 'passear'],
'Artigo 34º - Parágrafo 7º',
'warning',
'formal',
1,
ARRAY['Obrigatório coleira?', 'Pode soltar cachorro?', 'Precisa focinheira'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 92
('Cachorro pode fazer cocô na área comum?',
'Só se você RECOLHER IMEDIATAMENTE com saco plástico. Deixar fezes é infração grave que gera multa. Use sempre a área pet quando possível.',
'animais_passeio',
ARRAY['fezes', 'limpeza', 'multa'],
ARRAY['coco', 'fezes', 'xixi', 'sujeira', 'recolher'],
'Artigo 34º - Parágrafo 4º',
'warning',
'urgent',
1,
ARRAY['Cachorro fez cocô', 'Recolher fezes obrigatório?', 'Saco de cocô'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 93
('Onde fica a área pet?',
'O condomínio possui área pet específica para recreação dos animais, funcionando das 06h às 00h (meia-noite). Consulte a portaria sobre localização exata.',
'animais_passeio',
ARRAY['area pet', 'localizacao', 'horario'],
ARRAY['area pet', 'espacinho', 'cachorro', 'local', 'onde'],
'Artigo 34º - Parágrafo 9º',
'simple',
'friendly',
2,
ARRAY['Tem espaço para cachorro?', 'Onde levar meu pet?', 'Área pet do condomínio'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 94
('Meu cachorro é manso, precisa focinheira?',
'Depende do porte e raça. Cães de médio e grande porte devem usar focinheira. Cães pequenos podem ser dispensados, mas coleira é sempre obrigatória.',
'animais_passeio',
ARRAY['focinheira', 'porte', 'regras'],
ARRAY['focinheira', 'mordida', 'tamanho', 'pequeno', 'grande'],
'Artigo 34º - Parágrafo 7º',
'simple',
'formal',
2,
ARRAY['Obrigatório focinheira?', 'Cachorro pequeno precisa?', 'Focinheira sempre'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 95
('Cachorro latindo muito no passeio',
'Controle seu animal. Latidos excessivos perturbam o sossego dos demais moradores e podem gerar reclamações. Treine ou consulte veterinário comportamental.',
'animais_passeio',
ARRAY['latido', 'barulho', 'perturbacao'],
ARRAY['latido', 'late', 'barulho', 'perturbacao', 'incomodo'],
'Artigo 34º - Parágrafo 8º',
'conflict',
'formal',
2,
ARRAY['Cachorro late muito', 'Late no passeio', 'Perturbação por latido'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 96
('Cachorro pulou em pessoa no condomínio',
'Você é 100% responsável. Se houver dano (roupa rasgada, arranhão, susto), deve indenizar. Mantenha sempre seu animal sob controle.',
'animais_passeio',
ARRAY['acidente', 'responsabilidade', 'dano'],
ARRAY['pulou', 'arranhou', 'machucou', 'responsavel', 'indenizar'],
'Artigo 34º - Parágrafo 6º',
'conflict',
'formal',
1,
ARRAY['Cachorro atacou alguém', 'Animal pulou em vizinho', 'Acidente com pet'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 97
('Posso passear com meu gato?',
'Sim, desde que use coleira/guia apropriada para gatos (tipo peitoral). Gatos devem estar sempre sob controle.',
'animais_passeio',
ARRAY['gato', 'passeio', 'permitido'],
ARRAY['gato', 'coleira', 'guia', 'passear', 'felino'],
'Artigo 34º',
'simple',
'friendly',
3,
ARRAY['Gato pode passear?', 'Coleira em gato?', 'Levar gato para fora'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 98
('Cachorro do vizinho sempre solto',
'Registre no livro de ocorrências ou comunique ao síndico. Cães soltos sem coleira são infração ao regimento. O dono pode ser advertido/multado.',
'animais_passeio',
ARRAY['denuncia', 'infracão', 'cachorro solto'],
ARRAY['solto', 'sem coleira', 'denuncia', 'vizinho', 'irregular'],
'Artigos 34º §7º e 79º',
'conflict',
'formal',
2,
ARRAY['Cachorro sem coleira', 'Denunciar pet solto', 'Animal perigoso solto'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 99
('Meu cachorro brigou com outro no condomínio',
'Separe imediatamente. Ambos os donos são responsáveis. Se houver ferimentos, busque veterinário. Comunique o incidente ao síndico. Custos de tratamento são compartilhados ou determinados conforme culpa.',
'animais_passeio',
ARRAY['briga', 'acidente', 'veterinario'],
ARRAY['briga', 'mordida', 'ataque', 'ferimento', 'veterinario'],
'Artigo 34º - Parágrafo 6º',
'emergency',
'urgent',
1,
ARRAY['Cachorros brigaram', 'Animal mordido', 'Briga de pets'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 100
('Posso passear de madrugada?',
'Sim, mas evite latidos e barulhos que perturbem o sono dos moradores. Horário de silêncio é 22h-6h (23h-8h em julho/dez/jan).',
'animais_passeio',
ARRAY['madrugada', 'horario', 'silencio'],
ARRAY['madrugada', 'noite', 'tarde', 'horario', 'silencio'],
'Artigos 1º e 34º',
'simple',
'friendly',
3,
ARRAY['Passear à noite', 'Horário para cachorro', 'Madrugada com pet'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 101
('Cachorro fugiu, o que fazer?',
'Comunique IMEDIATAMENTE à portaria. Avise no grupo de WhatsApp dos moradores. Faça boletim de ocorrência. Procure em abrigos/clínicas próximas. Peça ajuda na vizinhança.',
'animais_passeio',
ARRAY['fuga', 'emergencia', 'procedimento'],
ARRAY['fugiu', 'perdido', 'sumiu', 'procurar', 'encontrar'],
'Artigo 29º (responsabilidade)',
'emergency',
'urgent',
1,
ARRAY['Pet fugiu', 'Cachorro perdido', 'Não acho meu animal'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 102
('Achei um cachorro perdido no condomínio',
'Leve à portaria. Tire foto e divulgue no grupo dos moradores. Se ninguém reclamar, procure ONGs de proteção animal. Não abandone.',
'animais_passeio',
ARRAY['achado', 'perdido', 'procedimento'],
ARRAY['achei', 'encontrei', 'perdido', 'abandonado', 'socorro'],
'Artigo 12º (objetos achados)',
'procedural',
'friendly',
2,
ARRAY['Cachorro abandonado', 'Encontrei pet', 'Animal sem dono'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 103
('Posso dar banho no cachorro na área comum?',
'Não. Banho deve ser dado dentro da sua unidade ou em pet shop. Não use torneiras/mangueiras de área comum para lavar animais.',
'animais_passeio',
ARRAY['banho', 'proibicao', 'area comum'],
ARRAY['banho', 'lavar', 'mangueira', 'torneira', 'agua'],
'Artigo 50º (uso inadequado)',
'warning',
'formal',
2,
ARRAY['Lavar cachorro na área comum', 'Banho de pet', 'Usar mangueira para pet'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 104
('Cachorro está muito doente para passear',
'Não force. Espere recuperação ou use tapete higiênico. Se necessário sair (veterinário), carregue no colo. Comunique síndico se for doença contagiosa.',
'animais_passeio',
ARRAY['doenca', 'saude', 'cuidados'],
ARRAY['doente', 'doenca', 'veterinario', 'saude', 'tapete'],
'Artigo 34º',
'educational',
'friendly',
3,
ARRAY['Pet doente', 'Cachorro não pode andar', 'Animal enfermo'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 105
('Cachorro grande pode usar elevador?',
'Sim, mas use focinheira obrigatória. Se houver outras pessoas com medo, seja educado: espere o próximo elevador. Em horário de pico, evite.',
'animais_passeio',
ARRAY['elevador', 'etiqueta', 'convivencia'],
ARRAY['elevador', 'grande', 'focinheira', 'medo', 'pessoas'],
'Artigo 34º §7º',
'simple',
'friendly',
2,
ARRAY['Pet no elevador', 'Elevador com cachorro', 'Cachorro grande pode'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 106
('Vizinho tem medo do meu cachorro',
'Respeite. Use coleira curta, focinheira se necessário, mantenha distância. Não force aproximação. Empatia é fundamental para boa convivência.',
'animais_passeio',
ARRAY['convivencia', 'respeito', 'medo'],
ARRAY['medo', 'fobia', 'respeito', 'distancia', 'convivencia'],
'Artigo 65º (respeito mútuo)',
'educational',
'friendly',
3,
ARRAY['Pessoa com medo de cachorro', 'Vizinho fóbico', 'Respeitar quem tem medo'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 107
('Posso soltar 2 cachorros juntos?',
'Sim, desde que ambos sejam seus (limite de 2 animais por casa) e estejam sob seu controle. Use coleiras duplas ou guia única com dois animais.',
'animais_passeio',
ARRAY['multiplos', 'passeio', 'controle'],
ARRAY['dois', 'dois cachorros', 'duplo', 'juntos', 'varios'],
'Artigo 34º §1º',
'simple',
'friendly',
3,
ARRAY['Passear com 2 cachorros', 'Dois pets juntos', 'Levar ambos'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 108
('Criança pode passear com cachorro sozinha?',
'Não é recomendado. Criança menor de 12 anos não tem força/maturidade para controlar um cão em emergência. Sempre um adulto responsável deve acompanhar.',
'animais_passeio',
ARRAY['crianca', 'seguranca', 'supervisao'],
ARRAY['crianca', 'filho', 'menor', 'sozinho', 'passear'],
'Artigo 66º (supervisão)',
'warning',
'formal',
2,
ARRAY['Filho pode passear com pet', 'Criança com cachorro', 'Menor com animal'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 109
('Empregada pode passear com meu cachorro?',
'Sim, mas ela deve seguir todas as regras (coleira, focinheira, recolher fezes). Você continua responsável por qualquer problema.',
'animais_passeio',
ARRAY['empregada', 'responsabilidade', 'delegacao'],
ARRAY['empregada', 'funcionaria', 'baba', 'dog walker', 'terceiro'],
'Artigo 34º',
'simple',
'friendly',
3,
ARRAY['Funcionária passear com pet', 'Delegar passeio', 'Dog walker'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 110
('Cachorro está velho e com dificuldade de andar',
'Use carrinho para pets ou carregue no colo. Se ele precisa fazer necessidades e não consegue andar, considere tapete higiênico ou fraldas. Consulte veterinário sobre qualidade de vida.',
'animais_passeio',
ARRAY['idoso', 'saude', 'cuidados'],
ARRAY['velho', 'idoso', 'dificuldade', 'artrose', 'carrinho'],
'Artigo 34º',
'educational',
'friendly',
3,
ARRAY['Pet idoso', 'Cachorro com artrose', 'Dificuldade de locomoção'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96');

-- ============================================================================
-- CATEGORIA 5: ANIMAIS - RESTRIÇÕES (15 FAQs: 111-125)
-- ============================================================================

INSERT INTO public.faqs (question, answer, category, tags, keywords, article_reference, scenario_type, tone, priority, question_variations, condominio_id, has_legal_implications) VALUES

-- Pergunta 111
('Quantos animais posso ter?',
'Máximo de 2 animais de companhia (cães, gatos) por unidade autônoma. Outras espécies precisam aprovação em assembleia.',
'animais_restricoes',
ARRAY['limite', 'quantidade', 'regras'],
ARRAY['quantos', 'limite', 'maximo', 'varios', 'quantidade'],
'Artigo 34º - Parágrafo 1º',
'simple',
'formal',
1,
ARRAY['Limite de pets', 'Posso ter 3 cachorros?', 'Quantos animais permitidos'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 112
('Posso ter pit bull?',
'Depende. Animais de grande porte ou notória agressividade podem ser proibidos. Pit bulls, rottweilers e raças similares devem ser avaliados caso a caso pelo síndico. Use sempre focinheira.',
'animais_restricoes',
ARRAY['pit bull', 'raca', 'restricao'],
ARRAY['pit bull', 'rottweiler', 'perigoso', 'agressivo', 'raça'],
'Artigo 55º',
'warning',
'formal',
1,
ARRAY['Raça perigosa permitida?', 'Rottweiler pode?', 'Cachorro agressivo'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
true),

-- Pergunta 113
('Meu cachorro é de grande porte, pode entrar?',
'Sim, mas com restrições: coleira forte, focinheira obrigatória, recolhimento de fezes, controle rigoroso. Cães muito grandes (acima de 40kg) podem ter restrições adicionais.',
'animais_restricoes',
ARRAY['grande porte', 'restricoes', 'regras'],
ARRAY['grande', 'grandão', 'enorme', 'tamanho', 'peso'],
'Artigo 34º §7º',
'simple',
'formal',
2,
ARRAY['Cachorro gigante pode?', 'Animal muito grande', 'Porte restrito'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 114
('Posso ter pássaro?',
'Sim, pássaros são permitidos, mas devem estar sempre em gaiola/viveiro. Não podem gerar incômodo sonoro (canto excessivo). Espécies silvestres precisam documentação do IBAMA.',
'animais_restricoes',
ARRAY['passaro', 'ave', 'permitido'],
ARRAY['passaro', 'ave', 'papagaio', 'periquito', 'canario'],
'Artigo 34º §2º',
'simple',
'friendly',
3,
ARRAY['Pode ter passarinho?', 'Papagaio é permitido?', 'Criar ave'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
true),

-- Pergunta 115
('Posso ter coelho?',
'Outras espécies além de cães e gatos estão sujeitas a aprovação em assembleia, com quórum de 2/3 dos condôminos presentes.',
'animais_restricoes',
ARRAY['coelho', 'exotico', 'aprovacao'],
ARRAY['coelho', 'roedor', 'hamster', 'porquinho', 'exotico'],
'Artigo 34º - Parágrafo 2º',
'procedural',
'formal',
3,
ARRAY['Roedor permitido?', 'Hamster pode?', 'Animal diferente'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 116
('Meu cachorro late muito, vão me multar?',
'Sim, se houver reclamações. Latidos que perturbem o sossego geram advertência e, se persistirem, multa. Treine o animal ou consulte veterinário comportamental.',
'animais_restricoes',
ARRAY['latido', 'perturbacao', 'multa'],
ARRAY['late', 'latido', 'barulho', 'multa', 'reclamacao'],
'Artigos 34º §8º e 79º',
'conflict',
'warning',
1,
ARRAY['Cachorro late demais', 'Reclamação de latido', 'Barulho de pet'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 117
('Cachorro fazendo xixi no elevador',
'Limpe IMEDIATAMENTE com água e desinfetante. Você é responsável pela higiene. Reincidência gera multa. Treine seu animal.',
'animais_restricoes',
ARRAY['higiene', 'elevador', 'multa'],
ARRAY['xixi', 'urina', 'coco', 'elevador', 'limpar'],
'Artigos 34º e 79º',
'conflict',
'urgent',
1,
ARRAY['Pet fez xixi no elevador', 'Cachorro urinou', 'Limpeza de fezes'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 118
('Posso criar galinha?',
'Não. Criação de animais de produção (galinhas, patos, porcos) é proibida em condomínios residenciais urbanos por questões sanitárias.',
'animais_restricoes',
ARRAY['galinha', 'proibicao', 'producao'],
ARRAY['galinha', 'pato', 'porco', 'producao', 'fazenda'],
'Artigo 34º',
'warning',
'formal',
2,
ARRAY['Ter galinha pode?', 'Criar ave de produção', 'Galinheiro permitido'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
true),

-- Pergunta 119
('Vizinho tem mais de 2 animais',
'Registre reclamação no livro de ocorrências ou comunique ao síndico. O limite é de 2 animais. Excesso pode gerar notificação para regularizar.',
'animais_restricoes',
ARRAY['denuncia', 'excesso', 'limite'],
ARRAY['muitos', 'excesso', 'varios', 'denuncia', 'irregular'],
'Artigos 34º §1º e 79º',
'conflict',
'formal',
2,
ARRAY['Vizinho com muitos pets', 'Denunciar excesso de animais', 'Casa com 5 cachorros'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 120
('Meu cachorro é de raça "perigosa" mas super dócil',
'A classificação é por potencial, não comportamento individual. Mesmo dócil, deve usar focinheira e seguir regras específicas. É questão de segurança preventiva.',
'animais_restricoes',
ARRAY['raca perigosa', 'docil', 'restricoes'],
ARRAY['docil', 'manso', 'perigoso', 'raça', 'focinheira'],
'Artigo 55º',
'educational',
'formal',
2,
ARRAY['Pit bull manso', 'Cachorro calmo mas grande', 'Raça listada'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
true),

-- Pergunta 121
('Posso ter réptil?',
'Cobras, lagartos e répteis exóticos dependem de aprovação em assembleia e documentação legal (IBAMA). Animais venenosos ou perigosos são sempre proibidos.',
'animais_restricoes',
ARRAY['reptil', 'exotico', 'restricao'],
ARRAY['cobra', 'lagarto', 'reptil', 'iguana', 'exotico'],
'Artigo 34º §2º',
'warning',
'formal',
2,
ARRAY['Cobra permitida?', 'Iguana pode ter?', 'Animal exótico'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
true),

-- Pergunta 122
('Cachorro está agressivo com todo mundo',
'É sua responsabilidade controlar. Se houver reclamações de comportamento agressivo, o síndico pode exigir treinamento profissional. Casos graves: remoção do animal.',
'animais_restricoes',
ARRAY['agressividade', 'problema', 'risco'],
ARRAY['agressivo', 'morde', 'ataca', 'perigoso', 'problema'],
'Artigos 34º §6º e 55º',
'conflict',
'urgent',
1,
ARRAY['Pet agressivo', 'Cachorro ataca pessoas', 'Animal violento'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 123
('Posso ter peixe?',
'Sim, aquários são permitidos sem restrições. Cuide para evitar vazamentos que danifiquem a estrutura.',
'animais_restricoes',
ARRAY['peixe', 'aquario', 'permitido'],
ARRAY['peixe', 'aquario', 'betta', 'guppy', 'ornamental'],
'Artigo 34º',
'simple',
'friendly',
4,
ARRAY['Aquário pode?', 'Ter peixinho', 'Peixes ornamentais'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 124
('Quero criar gato, tem limite?',
'Sim, o limite de 2 animais vale também para gatos. Você pode ter: 2 gatos, 2 cães, ou 1 de cada.',
'animais_restricoes',
ARRAY['gato', 'limite', 'quantidade'],
ARRAY['gato', 'felino', 'limite', 'quantos', 'dois'],
'Artigo 34º §1º',
'simple',
'friendly',
2,
ARRAY['Quantos gatos posso ter?', 'Limite de felinos', '2 gatos podem'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false),

-- Pergunta 125
('Animal fazendo muito barulho à noite',
'Latidos, miados ou ruídos de animais durante horário de silêncio (22h-6h) são infração. Se for seu animal, controle. Se for do vizinho, registre reclamação.',
'animais_restricoes',
ARRAY['barulho', 'noite', 'perturbacao'],
ARRAY['barulho', 'noite', 'madrugada', 'late', 'mia'],
'Artigos 1º, 34º §8º',
'conflict',
'warning',
1,
ARRAY['Pet late de madrugada', 'Barulho de animal à noite', 'Silêncio noturno'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96',
false);

-- ============================================================================
-- CATEGORIA 6: FINANCEIRO - PAGAMENTO (25 FAQs: 126-150)
-- ============================================================================

INSERT INTO public.faqs (question, answer, category, tags, keywords, article_reference, scenario_type, tone, priority, question_variations, condominio_id) VALUES

-- Pergunta 126
('Quando vence a taxa de condomínio?',
'Todo dia 15 de cada mês. Pagamentos após essa data sofrem incidência de multa de 2% + juros de mora de 1% ao mês.',
'financeiro_pagamento',
ARRAY['vencimento', 'prazo', 'data'],
ARRAY['vencimento', 'dia', 'quando', 'prazo', 'data'],
'Artigo 71º',
'simple',
'friendly',
1,
ARRAY['Dia de vencimento', 'Data do boleto', 'Prazo de pagamento'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 127
('Não recebi o boleto',
'Entre em contato com a administradora. Você pode acessar o boleto pelo site/app da Predial Administradora ou solicitar segunda via. Não receber o boleto NÃO isenta da multa.',
'financeiro_pagamento',
ARRAY['boleto', 'segunda via', 'problema'],
ARRAY['boleto', 'nao recebi', 'segunda via', 'email', 'correio'],
'Artigo 72º',
'procedural',
'friendly',
2,
ARRAY['Boleto não chegou', 'Como pegar segunda via', 'Não recebi cobrança'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 128
('Posso pagar depois do dia 15?',
'Pode, mas haverá cobrança de multa (2%) + juros (1% ao mês). O ideal é sempre pagar dentro do prazo.',
'financeiro_pagamento',
ARRAY['atraso', 'multa', 'juros'],
ARRAY['atraso', 'depois', 'atrasado', 'multa', 'juros'],
'Artigo 71º',
'simple',
'warning',
2,
ARRAY['Atrasei o pagamento', 'Posso pagar atrasado', 'Multa por atraso'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 129
('Como pagar o boleto atrasado?',
'Entre em contato com a administradora para receber boleto atualizado com multa e juros. Não pague o valor antigo, pois ficará com saldo devedor.',
'financeiro_pagamento',
ARRAY['boleto', 'atraso', 'procedimento'],
ARRAY['atrasado', 'vencido', 'pagar', 'multa', 'atualizado'],
'Artigo 72º',
'procedural',
'formal',
2,
ARRAY['Boleto vencido como pagar', 'Atualizar boleto', 'Pagar com multa'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 130
('Posso parcelar a taxa de condomínio?',
'Isso depende de negociação com a administradora e aprovação do síndico. Em casos de dificuldade financeira, procure a administração para negociar.',
'financeiro_pagamento',
ARRAY['parcelamento', 'negociacao', 'divida'],
ARRAY['parcelar', 'dividir', 'pagamento', 'negociar', 'parcela'],
'Artigo 72º',
'procedural',
'formal',
3,
ARRAY['Dividir em parcelas', 'Negociar dívida', 'Acordo de pagamento'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 131
('Estou desempregado, posso ter desconto?',
'Não há previsão de desconto no regimento. Procure a administradora para tentar negociar prazo ou parcelamento, mas taxa condominial é obrigatória.',
'financeiro_pagamento',
ARRAY['dificuldade', 'desconto', 'negociacao'],
ARRAY['desempregado', 'desconto', 'isencao', 'dificuldade', 'financeira'],
'Artigo 71º',
'educational',
'formal',
3,
ARRAY['Tenho desconto?', 'Isenção por desemprego', 'Redução de taxa'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 132
('Onde vejo meu extrato?',
'Acesse o menu Transparência > Financeiro no app do condomínio, ou portal da Predial Administradora com seu login.',
'financeiro_pagamento',
ARRAY['extrato', 'transparencia', 'acesso'],
ARRAY['extrato', 'comprovante', 'historico', 'pagamento', 'portal'],
'Artigo 70º - II',
'procedural',
'friendly',
2,
ARRAY['Ver meus pagamentos', 'Histórico financeiro', 'Comprovantes'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 133
('Paguei mas aparece pendente',
'Aguarde 3 dias úteis para compensação bancária. Se persistir, entre em contato com a administradora levando comprovante de pagamento.',
'financeiro_pagamento',
ARRAY['pagamento', 'compensacao', 'problema'],
ARRAY['paguei', 'compensar', 'pendente', 'demora', 'comprovante'],
'Artigo 72º',
'procedural',
'friendly',
2,
ARRAY['Pagamento não compensou', 'Ainda aparece dívida', 'Comprovante não baixou'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 134
('Comprei apartamento com dívida',
'Você responde pelos débitos anteriores (Art. 1345 do Código Civil). É fundamental checar a Certidão Negativa de Débitos (CND) ANTES de comprar. Procure advogado.',
'financeiro_pagamento',
ARRAY['compra', 'divida anterior', 'legal'],
ARRAY['compra', 'comprei', 'divida', 'anterior', 'vendedor'],
'Artigo 75º e Código Civil Art. 1345',
'warning',
'urgent',
1,
ARRAY['Apartamento com dívida', 'Débito do antigo dono', 'Comprei com pendência'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 135
('Posso pagar no PIX?',
'Verifique com a administradora se há chave PIX disponível. Sempre peça confirmação e guarde comprovante.',
'financeiro_pagamento',
ARRAY['pix', 'pagamento', 'metodo'],
ARRAY['pix', 'transferencia', 'forma', 'pagamento', 'chave'],
'Artigo 72º',
'simple',
'friendly',
3,
ARRAY['Como pagar por PIX', 'Tem PIX do condomínio', 'Transferência permitida'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 136
('O que está incluído na taxa?',
'Taxa condominial cobre: manutenção de áreas comuns, salários de funcionários, água/luz de áreas comuns, limpeza, segurança, reserva para emergências. Veja discriminação no boleto.',
'financeiro_pagamento',
ARRAY['composicao', 'taxa', 'itens'],
ARRAY['inclui', 'o que é', 'composicao', 'discriminacao', 'rateio'],
'Artigo 70º - II (prestação de contas)',
'educational',
'friendly',
3,
ARRAY['O que pago no condomínio', 'Para que serve a taxa', 'Itens do boleto'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 137
('Taxa subiu muito este mês',
'Consulte a prestação de contas no app (menu Transparência). O síndico deve apresentar justificativa até o dia 15. Pode ter havido obra emergencial, aumento de fornecedor, etc.',
'financeiro_pagamento',
ARRAY['aumento', 'valor', 'reclamacao'],
ARRAY['subiu', 'aumento', 'caro', 'mais alto', 'porque'],
'Artigos 70º-II e 63º',
'procedural',
'formal',
2,
ARRAY['Por que aumentou', 'Taxa mais cara', 'Valor subiu'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 138
('Moro sozinho, pago menos?',
'Não. Taxa condominial é por UNIDADE, não por número de moradores. Todos pagam o mesmo valor base.',
'financeiro_pagamento',
ARRAY['valor', 'proporcional', 'regra'],
ARRAY['sozinho', 'proporcional', 'menos', 'familia', 'pessoas'],
'Código Civil Art. 1336',
'educational',
'formal',
3,
ARRAY['Taxa proporcional', 'Sozinho paga menos', 'Valor por pessoa'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 139
('Estou viajando, não preciso pagar?',
'Precisa. Taxa condominial é obrigatória independente de uso. Você está pagando pela manutenção do patrimônio, não pelo uso.',
'financeiro_pagamento',
ARRAY['viagem', 'obrigacao', 'uso'],
ARRAY['viajando', 'fora', 'ausente', 'nao uso', 'obrigatorio'],
'Código Civil Art. 1336',
'educational',
'formal',
2,
ARRAY['Não uso não pago', 'Férias não pago', 'Ausente isenta'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Pergunta 140
('Quem cobra a taxa de condomínio?',
'A Predial Administradora arrecada. Se necessário, ela promove cobrança judicial em nome do condomínio.',
'financeiro_pagamento',
ARRAY['cobranca', 'administradora', 'responsavel'],
ARRAY['cobra', 'cobranca', 'administradora', 'responsavel', 'judicial'],
'Artigo 72º',
'simple',
'formal',
3,
ARRAY['Quem cobra a mensalidade', 'Administradora cobra', 'Responsável pela cobrança'],
'5c624180-5fca-41fd-a5a0-a6e724f45d96'),

-- Continuando as 25 FAQs de Financeiro-Pagamento... (141-150)

-- Por questão de espaço, vou resumir as próximas e continuar com as outras categorias.
-- Posso continuar o arquivo completo?
