-- ============================================================================
-- VERSIX NORMA - ARQUIVO DEFINITIVO FINAL: 130 FAQs (171-300)
-- ============================================================================
-- Este é o ÚLTIMO arquivo SQL. Execute após os 3 anteriores.
-- Completa o sistema com 300 FAQs totais optimizadas para RAG
-- ============================================================================

-- ============================================================================
-- CATEGORIA 8: SEGURANÇA - ACESSO (20 FAQs: 171-190)
-- ============================================================================

INSERT INTO public.faqs (question, answer, category, tags, keywords, article_reference, scenario_type, tone, priority, question_variations, condominio_id) VALUES

('Como autorizo entrada de visitante?', 'O visitante deve se anunciar na portaria, informando seu nome e qual unidade vai visitar. Você autoriza por interfone/telefone. O porteiro registra nome e horário.', 'seguranca_acesso', ARRAY['visitante', 'autorizacao', 'portaria'], ARRAY['visitante', 'autorizar', 'portaria', 'entrada', 'interfone'], 'Artigo 81º', 'procedural', 'friendly', 1, ARRAY['Como liberar visita', 'Autorizar pessoa', 'Visitante na portaria'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Entregador pode entrar sem autorização?', 'Não. Entregadores de iFood, Correios, gás, etc. SÓ entram com sua autorização prévia. É obrigatória a retirada do capacete.', 'seguranca_acesso', ARRAY['entregador', 'delivery', 'seguranca'], ARRAY['entregador', 'ifood', 'delivery', 'motoboy', 'capacete'], 'Artigo 8º - Parágrafo Único', 'warning', 'formal', 1, ARRAY['iFood pode entrar', 'Delivery no condomínio', 'Motoboy entra'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Porteiro pode exigir minha identidade?', 'Sim, a qualquer hora. Mesmo sendo morador, por segurança, o porteiro pode solicitar identificação, especialmente à noite ou com novo porteiro.', 'seguranca_acesso', ARRAY['identificacao', 'porteiro', 'seguranca'], ARRAY['identidade', 'rg', 'documento', 'porteiro', 'exigir'], 'Artigo 80º', 'simple', 'formal', 2, ARRAY['Mostrar RG ao porteiro', 'Identificação obrigatória', 'Porteiro pediu documento'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Posso dar acesso permanente para alguém?', 'Você pode cadastrar empregados domésticos e pessoas frequentes na portaria, mas a responsabilidade continua sendo sua.', 'seguranca_acesso', ARRAY['acesso', 'cadastro', 'permanente'], ARRAY['acesso permanente', 'cadastro', 'lista', 'frequente', 'empregada'], 'Artigos 9º e 67º', 'procedural', 'friendly', 2, ARRAY['Cadastrar empregada', 'Acesso liberado sempre', 'Lista permanente'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Estou esperando visita mas não atendo telefone', 'Informe previamente à portaria sobre visitas esperadas. Deixe instruções claras de quando liberar mesmo sem confirmar com você.', 'seguranca_acesso', ARRAY['visita', 'procedimento', 'comunicacao'], ARRAY['visita', 'telefone', 'atender', 'liberar', 'instrucao'], 'Artigo 81º', 'procedural', 'friendly', 3, ARRAY['Não posso atender telefone', 'Liberar sem confirmar', 'Visita programada'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Porteiro barrou minha visita sem motivo', 'O porteiro tem autonomia para barrar se houver suspeita fundada ou falta de autorização. Se foi abuso, registre reclamação ao síndico com detalhes.', 'seguranca_acesso', ARRAY['reclamacao', 'porteiro', 'conflito'], ARRAY['barrar', 'impedir', 'visitante', 'reclamacao', 'abuso'], 'Artigos 80º e 77º', 'conflict', 'formal', 2, ARRAY['Porteiro não deixou entrar', 'Impediu visita', 'Barrou sem razão'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Prestador de serviço pode entrar?', 'Sim, com autorização. Informe nome, empresa e serviço. Você responde por qualquer problema causado pelo prestador.', 'seguranca_acesso', ARRAY['prestador', 'servico', 'responsabilidade'], ARRAY['prestador', 'eletricista', 'encanador', 'servico', 'responsavel'], 'Artigo 46º', 'simple', 'friendly', 2, ARRAY['Eletricista pode entrar', 'Técnico externo', 'Prestador de serviço'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Posso entrar de Uber/táxi?', 'Sim, mas o motorista pode ser solicitado a se identificar. Informe previamente à portaria se for situação de urgência.', 'seguranca_acesso', ARRAY['uber', 'taxi', 'transporte'], ARRAY['uber', 'taxi', '99', 'motorista', 'transporte'], 'Artigo 80º', 'simple', 'friendly', 3, ARRAY['Uber entra no condomínio', 'Táxi pode entrar', 'Motorista de app'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Vizinho deixou desconhecido entrar', 'Comunique ao síndico. Cada morador responde por quem autoriza. Reforce a importância da segurança coletiva.', 'seguranca_acesso', ARRAY['seguranca', 'denuncia', 'vizinho'], ARRAY['desconhecido', 'suspeito', 'vizinho', 'liberou', 'seguranca'], 'Artigos 8º e 63º', 'conflict', 'formal', 2, ARRAY['Vizinho irresponsável', 'Libera qualquer um', 'Problema de segurança'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Câmeras do condomínio gravam quanto tempo?', 'Isso varia. Normalmente 30-90 dias. Consulte o síndico sobre a política de retenção de imagens e acesso conforme LGPD.', 'seguranca_acesso', ARRAY['cameras', 'gravacao', 'lgpd'], ARRAY['camera', 'video', 'gravacao', 'dias', 'lgpd'], 'Lei Geral de Proteção de Dados', 'educational', 'formal', 3, ARRAY['Tempo de gravação', 'Câmeras guardam quanto', 'Imagens antigas'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Posso pedir imagem das câmeras?', 'Sim, em casos específicos (acidente, furto, conflito). Faça solicitação formal ao síndico justificando a necessidade. Prazo de 3-7 dias úteis.', 'seguranca_acesso', ARRAY['cameras', 'acesso', 'procedimento'], ARRAY['imagem', 'video', 'camera', 'acessar', 'solicitar'], 'LGPD e Artigo 63º', 'procedural', 'formal', 2, ARRAY['Ver filmagem', 'Acessar gravação', 'Solicitar imagens'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Troquei de carro, preciso avisar?', 'Sim, atualize o cadastro na portaria com placa, modelo e cor. Facilita o acesso e segurança.', 'seguranca_acesso', ARRAY['veiculo', 'cadastro', 'atualizacao'], ARRAY['carro', 'veiculo', 'placa', 'cadastro', 'trocar'], 'Artigo 67º', 'simple', 'friendly', 3, ARRAY['Carro novo cadastro', 'Atualizar veículo', 'Mudei de carro'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Meu filho adolescente pode entrar sozinho?', 'Sim, desde que cadastrado. Informe à portaria que ele é morador. Ele pode precisar apresentar documento.',  'seguranca_acesso', ARRAY['adolescente', 'menor', 'cadastro'], ARRAY['adolescente', 'filho', 'menor', 'sozinho', 'cadastro'], 'Artigo 80º', 'simple', 'friendly', 2, ARRAY['Filho adolescente', 'Menor sozinho', 'Jovem morando'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Quero instalar interfone na portaria', 'Sugestões de melhorias devem ser apresentadas ao síndico ou em assembleia. Custos serão rateados se aprovado.', 'seguranca_acesso', ARRAY['interfone', 'melhoria', 'sugestao'], ARRAY['interfone', 'videoporteiro', 'instalar', 'sugestao', 'melhoria'], 'Artigos 63º e 85º', 'procedural', 'friendly', 4, ARRAY['Videoporteiro', 'Melhorar portaria', 'Sistema de interfone'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Porteiro dorme no turno', 'Registre no livro de ocorrências ou comunique ao síndico com horário específico. Funcionário pode ser advertido ou demitido.', 'seguranca_acesso', ARRAY['porteiro', 'denuncia', 'negligencia'], ARRAY['porteiro', 'dormir', 'cochilo', 'negligencia', 'reclamacao'], 'Artigos 45º e 63º', 'conflict', 'formal', 1, ARRAY['Porteiro negligente', 'Vigia dormindo', 'Segurança dormindo'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Tem controle de acesso biométrico?', 'Depende. Verifique com o síndico. Se não houver, pode sugerir em assembleia. Investimento precisa de aprovação.', 'seguranca_acesso', ARRAY['biometria', 'tecnologia', 'acesso'], ARRAY['biometria', 'digital', 'impressao digital', 'tecnologia', 'moderno'], 'Artigos 63º e 85º', 'simple', 'friendly', 4, ARRAY['Biometria na entrada', 'Digital para entrar', 'Tecnologia de acesso'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Convidado esqueceu documento', 'O porteiro tem autonomia para decidir. Pode permitir entrada com identificação alternativa (CNH digital, nome completo) ou negar acesso.', 'seguranca_acesso', ARRAY['documento', 'flexibilidade', 'procedimento'], ARRAY['documento', 'esqueceu', 'identidade', 'sem', 'alternativa'], 'Artigo 80º', 'simple', 'friendly', 3, ARRAY['Sem RG pode entrar', 'Visitante sem documento', 'Identificação alternativa'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Porteiro é grosseiro comigo', 'Registre reclamação formal ao síndico com detalhes (data, hora, testemunhas). Comportamento inadequado deve ser corrigido ou funcionário substituído.', 'seguranca_acesso', ARRAY['reclamacao', 'porteiro', 'atendimento'], ARRAY['grosseiro', 'mal educado', 'rude', 'comportamento', 'reclamacao'], 'Artigos 45º e 77º', 'conflict', 'formal', 2, ARRAY['Porteiro mal-educado', 'Atendimento ruim', 'Funcionário grosso'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Posso dar gorjeta ao porteiro?', 'Pode, mas não é obrigatório. Gorjetas são espontâneas. Não confunda com taxa de final de ano (13º salário), que é obrigatória e coletiva.', 'seguranca_acesso', ARRAY['gorjeta', 'porteiro', 'gratificacao'], ARRAY['gorjeta', 'gratificacao', '13 salario', 'natal', 'porteiro'], 'CLT', 'educational', 'friendly', 4, ARRAY['13º do porteiro', 'Gratificação de natal', 'Dar dinheiro ao funcionário'], '5c624180-5fca-41fd-a5a0-a6e724f45d96'),

('Esqueci a chave e porteiro não tem cópia', 'O condomínio NÃO guarda chaves das unidades. Você precisa chamar chaveiro particular. Custo é seu.', 'seguranca_acesso', ARRAY['chave', 'emergencia', 'procedimento'], ARRAY['chave', 'esqueci', 'copia', 'chaveiro', 'abrir'], 'Artigo 7º', 'procedural', 'friendly', 2, ARRAY['Tranquei fora', 'Perdi chave', 'Como entrar sem chave'], '5c624180-5fca-41fd-a5a0-a6e724f45d96');

-- ============================================================================
-- CATEGORIA 9: SEGURANÇA - EMERGÊNCIA (25 FAQs: 191-215)
-- ============================================================================

INSERT INTO public.faqs (question, answer, category, tags, keywords, article_reference, scenario_type, tone, priority, question_variations, condominio_id, requires_sindico_action, has_legal_implications) VALUES

('Princípio de incêndio, o que fazer?', 'LIGUE 193 (Bombeiros) IMEDIATAMENTE. Avise portaria para acionar alarme. Não use elevador. Saia pela escada. Use extintor apenas se souber (classe C para elétrico, A para comum).', 'seguranca_emergencia', ARRAY['incendio', 'bombeiros', 'procedimento'], ARRAY['fogo', 'incendio', 'queimando', '193', 'extintor'], 'Artigo 42º e Normas de Segurança', 'emergency', 'urgent', 1, ARRAY['Fogo no apartamento', 'Casa pegando fogo', 'Emergência de incêndio'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Vazamento grande de água', 'Feche IMEDIATAMENTE o registro geral da sua unidade. Avise portaria E síndico. Desligue eletricidade da área afetada. Você tem 12h para chamar encanador.', 'seguranca_emergencia', ARRAY['vazamento', 'agua', 'procedimento'], ARRAY['vazamento', 'agua', 'inundacao', 'registro', 'encanador'], 'Artigo 64º', 'emergency', 'urgent', 1, ARRAY['Casa alagando', 'Cano estourou', 'Água vazando muito'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Cheiro de gás no corredor', 'NÃO acenda luzes/fósforos. Abra janelas. Ligue 193 (Bombeiros) de local seguro. Avise todos os vizinhos. Evacue se necessário.', 'seguranca_emergencia', ARRAY['gas', 'explosao', 'perigo'], ARRAY['gas', 'cheiro', 'vazamento', '193', 'explosao'], 'Artigo 42º', 'emergency', 'urgent', 1, ARRAY['Vazamento de gás', 'Cheiro de gás forte', 'Risco de explosão'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Alguém está tendo infarto', 'Ligue 192 (SAMU) IMEDIATAMENTE. Mantenha a pessoa calma e deitada. Afrouxe roupas. Se parar de respirar, inicie RCP se souber. Avise portaria para facilitar entrada da ambulância.', 'seguranca_emergencia', ARRAY['saude', 'emergencia', 'samu'], ARRAY['infarto', 'ataque cardiaco', '192', 'samu', 'emergencia'], 'Artigo 41º', 'emergency', 'urgent', 1, ARRAY['Ataque cardíaco', 'Pessoa passando mal', 'Emergência médica'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', false, false),

('Pessoa suspeita dentro do condomínio', 'Comunique IMEDIATAMENTE à portaria. NÃO confronte. Ligue 190 (Polícia) se houver ameaça. Registre características (roupa, altura, direção).', 'seguranca_emergencia', ARRAY['suspeito', 'seguranca', 'policia'], ARRAY['suspeito', 'estranho', '190', 'policia', 'perigo'], 'Artigo 80º', 'emergency', 'urgent', 1, ARRAY['Invasor', 'Pessoa estranha', 'Suspeito no prédio'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Criança engoliu veneno', 'Ligue 192 (SAMU) e 0800-722-6001 (Centro de Informação Toxicológica) IMEDIATAMENTE. NÃO induza vômito. Leve a embalagem do produto. Avise portaria para ambulância.', 'seguranca_emergencia', ARRAY['intoxicacao', 'crianca', 'veneno'], ARRAY['veneno', 'intoxicacao', 'engoliu', 'crianca', '192'], 'Emergência Toxicológica', 'emergency', 'urgent', 1, ARRAY['Intoxicação infantil', 'Criança envenenada', 'Engoliu produto tóxico'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', false, false),

('Elevador parou com gente dentro', 'MANTENHA A CALMA. Acione botão de emergência. Ligue para portaria. Bombeiros: 193 se houver claustrofobia/pânico. Técnico virá (30min-2h). NÃO force portas.', 'seguranca_emergencia', ARRAY['elevador', 'preso', 'procedimento'], ARRAY['elevador', 'preso', 'parou', 'socorro', 'bombeiro'], 'Artigo 83º', 'emergency', 'urgent', 1, ARRAY['Preso no elevador', 'Elevador travou', 'Emergência elevador'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Curto-circuito/falta de energia', 'Desligue disjuntor geral. Não mexa em fios. Chame eletricista. Se for área comum, avise síndico. Se for emergência (fumaça/faísca), ligue 193.', 'seguranca_emergencia', ARRAY['eletrico', 'curto', 'energia'], ARRAY['curto', 'energia', 'falta luz', 'eletrico', 'disjuntor'], 'Artigo 64º', 'emergency', 'warning', 1, ARRAY['Energia caiu', 'Curto-circuito', 'Sem luz'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Animal agressivo solto', 'Mantenha distância. Ligue 190 (Polícia) ou Centro de Zoonoses. Avise portaria. Isole área. Identifique dono se possível.', 'seguranca_emergencia', ARRAY['animal', 'agressivo', 'perigo'], ARRAY['cachorro', 'agressivo', 'solto', 'ataque', '190'], 'Artigos 34º e 55º', 'emergency', 'urgent', 1, ARRAY['Cachorro perigoso', 'Animal atacando', 'Pit bull solto'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Meu vizinho está agredindo a mulher', 'Ligue 190 (Polícia Militar) IMEDIATAMENTE. Se for violência doméstica, ligue também 180 (Central da Mulher). Não se exponha. Registre B.O.', 'seguranca_emergencia', ARRAY['violencia domestica', 'policia', 'denuncia'], ARRAY['agressao', 'briga', 'violencia', '190', '180'], 'Lei Maria da Penha', 'emergency', 'urgent', 1, ARRAY['Violência doméstica', 'Vizinho batendo', 'Mulher apanhando'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', false, true),

('Tiros/tiroteio próximo', 'DEITE NO CHÃO longe de janelas. Não filme. Avise portaria. Ligue 190 após cessar perigo. Mantenha luzes apagadas.', 'seguranca_emergencia', ARRAY['tiroteio', 'tiro', 'procedimento'], ARRAY['tiro', 'tiroteio', 'bala', '190', 'perigo'], 'Protocolo de Segurança em Conflitos Armados', 'emergency', 'urgent', 1, ARRAY['Escutei tiros', 'Tiroteio próximo', 'Bala perdida'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', false, true),

('Estrutura do prédio rachou', 'Avise síndico URGENTEMENTE. Tire fotos. Ligue para Defesa Civil se for grande. Evacue área se risco de desabamento. Isso é GRAVE.', 'seguranca_emergencia', ARRAY['estrutura', 'rachadura', 'grave'], ARRAY['rachadura', 'estrutura', 'desabamento', 'risco', 'defesa civil'], 'Código de Edificações', 'emergency', 'urgent', 1, ARRAY['Rachadura grave', 'Parede rachada', 'Risco de desabar'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Enchente invadindo o condomínio', 'Desligue energia. Suba para andares altos. Ligue 193 (Bombeiros) e Defesa Civil. Ajude idosos/crianças. NÃO entre em água com fiação exposta.', 'seguranca_emergencia', ARRAY['enchente', 'alagamento', 'desastre'], ARRAY['enchente', 'inundacao', 'alagamento', '193', 'bombeiro'], 'Defesa Civil', 'emergency', 'urgent', 1, ARRAY['Alagamento', 'Enchente', 'Água subindo'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Criança sozinha perdida', 'Acalme a criança. Leve à portaria. Avise síndico. Conselho Tutelar se não achar pais: 100. Aguarde 1-2h antes de acionar autoridades.', 'seguranca_emergencia', ARRAY['crianca', 'perdida', 'procedimento'], ARRAY['crianca', 'perdida', 'sozinha', 'conselho tutelar', '100'], 'Estatuto da Criança e Adolescente', 'emergency', 'formal', 1, ARRAY['Menor perdido', 'Criança abandonada', 'Achou criança'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Idoso caído e sozinho', 'Ligue 192 (SAMU). NÃO mova (risco de fratura). Mantenha consciente. Avise família. Cubra com cobertor se frio. Aguarde socorro profissional.', 'seguranca_emergencia', ARRAY['idoso', 'queda', 'samu'], ARRAY['idoso', 'caiu', 'queda', '192', 'fratura'], 'Emergência Geriátrica', 'emergency', 'urgent', 1, ARRAY['Vovô caiu', 'Idoso machucado', 'Queda de idoso'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', false, false),

('Abelhas/vespas formaram colmeia', 'NÃO mexa. Isole área. Chame Bombeiros (193) ou empresa especializada. Evite perfumes/movimento brusco. Alérgicos: saia imediatamente.', 'seguranca_emergencia', ARRAY['abelha', 'vespa', 'perigo'], ARRAY['abelha', 'vespa', 'marimbondo', 'colmeia', '193'], 'Controle de Fauna Urbana', 'emergency', 'warning', 2, ARRAY['Enxame de abelhas', 'Marimbondos', 'Colmeia no prédio'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Cobra dentro do condomínio', 'Mantenha distância. Não tente pegar. Ligue Bombeiros (193) ou Centro de Controle de Zoonoses. Isole área. Fotos ajudam identificar se venenosa.', 'seguranca_emergencia', ARRAY['cobra', 'reptil', 'perigo'], ARRAY['cobra', 'serpente', 'venenosa', '193', 'zoonoses'], 'Controle de Zoonoses', 'emergency', 'urgent', 1, ARRAY['Serpente no condomínio', 'Cobra apareceu', 'Réptil perigoso'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Alguém tentou suicídio', 'Ligue 192 (SAMU) e 188 (CVV - Centro de Valorização da Vida) IMEDIATAMENTE. NÃO deixe sozinho. Retire objetos perigosos. Seja empático, não julgue.', 'seguranca_emergencia', ARRAY['suicidio', 'saude mental', 'cvv'], ARRAY['suicidio', 'depressao', '188', 'cvv', '192'], 'Centro de Valorização da Vida', 'emergency', 'urgent', 1, ARRAY['Tentativa de suicídio', 'Pessoa querendo se matar', 'Crise suicida'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', false, true),

('Vazamento de esgoto', 'Avise síndico URGENTE. Empresa especializada (não encanador comum). Risco de contaminação. Isole área. Use máscara. Desinfete após reparo.', 'seguranca_emergencia', ARRAY['esgoto', 'vazamento', 'contaminacao'], ARRAY['esgoto', 'vazamento', 'fossa', 'contaminacao', 'fedor'], 'Vigilância Sanitária', 'emergency', 'urgent', 1, ARRAY['Esgoto vazando', 'Contaminação', 'Cheiro de esgoto'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Roubaram dentro do condomínio', 'Ligue 190 (Polícia) IMEDIATAMENTE. NÃO mexa na cena. Registre B.O. Solicite imagens ao síndico. Avise vizinhos. Reforce segurança.', 'seguranca_emergencia', ARRAY['roubo', 'furto', 'policia'], ARRAY['roubo', 'furto', 'roubaram', '190', 'bo'], 'Código Penal', 'emergency', 'urgent', 1, ARRAY['Fui roubado', 'Furto no condomínio', 'Ladrão'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Dengue: foco do mosquito', 'Elimine água parada IMEDIATAMENTE. Avise síndico. Ligue Zoonoses para vistoria. Vizinhos devem colaborar. Dengue MATA.', 'seguranca_emergencia', ARRAY['dengue', 'mosquito', 'saude'], ARRAY['dengue', 'aedes', 'mosquito', 'agua parada', 'zoonoses'], 'Vigilância Sanitária', 'warning', 'urgent', 1, ARRAY['Mosquito da dengue', 'Foco de Aedes', 'Combate à dengue'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Morador com COVID', 'Isolamento de 7 dias. Avise síndico (opcional, para higienização reforçada de áreas comuns). Máscara obrigatória se sair. Teste após sintomas cessarem.', 'seguranca_emergencia', ARRAY['covid', 'doenca', 'isolamento'], ARRAY['covid', 'coronavirus', 'isolamento', 'mascara', 'doente'], 'Protocolo Sanitário COVID-19', 'warning', 'formal', 2, ARRAY['Peguei COVID', 'Coronavírus', 'Isolamento'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', false, true),

('Caixa d''água contaminada', 'NÃO BEBA. Avise síndico URGENTE. Empresa especializada para limpeza (obrigatória a cada 6 meses). Vigilância Sanitária pode interditar.', 'seguranca_emergencia', ARRAY['agua', 'contaminacao', 'caixa'], ARRAY['caixa agua', 'contaminacao', 'suja', 'potavel', 'doenca'], 'Vigilância Sanitária', 'emergency', 'urgent', 1, ARRAY['Água suja', 'Água contaminada', 'Caixa d''água'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, true),

('Portão automático não abre', 'Há abertura manual (chave/alavanca). Procure porteiro. Se emergência (ambulância), portaria abre manualmente. Técnico virá reparar.', 'seguranca_emergencia', ARRAY['portao', 'problema', 'acesso'], ARRAY['portao', 'automatico', 'emperrado', 'nao abre', 'manual'], 'Artigo 63º', 'simple', 'friendly', 2, ARRAY['Portão travado', 'Portão não funciona', 'Abertura manual'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false),

('Barulho de explosão no prédio', 'Saia da unidade. Vá para área aberta. Ligue 193 (Bombeiros). Não use elevador. Aguarde vistoria técnica. Pode ser gás, curto ou estrutura.', 'seguranca_emergencia', ARRAY['explosao', 'barulho', 'perigo'], ARRAY['explosao', 'estouro', 'barulho', 'forte', '193'], 'Protocolo de Emergência', 'emergency', 'urgent', 1, ARRAY['Estouro forte', 'Barulho de explosão', 'Algo estourou'], '5c624180-5fca-41fd-a5a0-a6e724f45d96', true, false);

-- ============================================================================
-- CATEGORIAS 10-20: COMPACTADAS (PERGUNTAS 216-300)
-- ============================================================================
-- Por questão de espaço, as próximas 85 FAQs serão criadas em formato compacto
-- mas mantendo qualidade e variação

-- CATEGORIA 10: OBRAS - PEQUENAS (15 FAQs: 216-230)
INSERT INTO public.faqs (question, answer, category, tags, keywords, priority, condominio_id) VALUES
('Posso pintar minha casa?', 'Sim, sem aviso. Interna é livre. Externa (fachada) precisa manter padrão do condomínio.', 'obras_pequenas', ARRAY['pintura', 'reforma', 'permitido'], ARRAY['pintar', 'cor', 'tinta', 'fachada'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Preciso avisar pequena reforma?', 'Sim. Qualquer reforma deve ser comunicada ao síndico, mesmo pequena (trocar pia, armário embutido).', 'obras_pequenas', ARRAY['reforma', 'comunicacao', 'obrigacao'], ARRAY['avisar', 'reforma', 'pequena', 'sindico'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Horário para obras?', 'Segunda a sexta: 8h-12h e 14h-18h. Sábado: 8h-12h. Proibido domingo e feriados.', 'obras_pequenas', ARRAY['horario', 'obra', 'barulho'], ARRAY['horario', 'obra', 'trabalhar', 'domingo'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Entulho de obra onde jogar?', 'Contrate caçamba particular. Proibido misturar com lixo comum. Custo é seu.', 'obras_pequenas', ARRAY['entulho', 'lixo', 'obra'], ARRAY['entulho', 'caçamba', 'lixo', 'obra', 'contratar'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Posso trocar piso?', 'Sim. Avise síndico. Use proteção em elevador/corredores durante transporte.', 'obras_pequenas', ARRAY['piso', 'troca', 'reforma'], ARRAY['piso', 'ceramica', 'trocar', 'chao'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Martelando muito, posso ser multado?', 'Sim, se ultrapassar horários permitidos ou fazer muito barulho por muitos dias seguidos.', 'obras_pequenas', ARRAY['barulho', 'multa', 'martelo'], ARRAY['barulho', 'martelo', 'multa', 'incomodo'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Pedreiro pode circular?', 'Sim, mas sem ferramentas aparentes em áreas comuns. Proteção em elevador é obrigatória.', 'obras_pequenas', ARRAY['pedreiro', 'obra', 'acesso'], ARRAY['pedreiro', 'circulação', 'obra', 'funcionario'], 3, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Posso mexer na janela?', 'Externa: NÃO (altera fachada). Interna: SIM (vidro, esquadria interna).', 'obras_pequenas', ARRAY['janela', 'fachada', 'restricao'], ARRAY['janela', 'trocar', 'vidro', 'esquadria'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Instalação de ar condicionado', 'Permitido, mas siga padrão de instalação do condomínio (condensadora em local específico).', 'obras_pequenas', ARRAY['ar condicionado', 'instalacao', 'padrao'], ARRAY['ar condicionado', 'split', 'instalar'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Vizinho fazendo obra há 3 meses', 'Comunique ao síndico. Obras longas precisam de cronograma e podem ter restrição de dias/semana.', 'obras_pequenas', ARRAY['obra longa', 'reclamacao', 'prazo'], ARRAY['obra', 'meses', 'muito tempo', 'reclamacao'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Posso instalar grade na janela?', 'Depende. Se alterar fachada, precisa aprovar em assembleia. Interna é livre.', 'obras_pequenas', ARRAY['grade', 'janela', 'seguranca'], ARRAY['grade', 'janela', 'proteção', 'seguranca'], 3, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Material de obra pode ficar no corredor?', 'NÃO. Materiais devem ficar dentro da unidade. Corredor é área comum e deve estar livre.', 'obras_pequenas', ARRAY['material', 'corredor', 'proibicao'], ARRAY['material', 'corredor', 'sacos', 'cimento'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Obra suja o corredor', 'Você é responsável pela limpeza diária. Não limpar gera advertência/multa.', 'obras_pequenas', ARRAY['limpeza', 'corredor', 'obra'], ARRAY['sujeira', 'poeira', 'limpar', 'corredor'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Posso fazer obra à noite?', 'NÃO. Horários de silêncio (22h-6h) devem ser respeitados. Infração grave.', 'obras_pequenas', ARRAY['noite', 'proibicao', 'obra'], ARRAY['noite', 'madrugada', 'obra', 'barulho'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Pequeno conserto precisa avisar?', 'Consertos rápidos (trocar torneira, repintura) não precisam. Obras que geram barulho/entulho: avisar.', 'obras_pequenas', ARRAY['conserto', 'aviso', 'procedimento'], ARRAY['conserto', 'reparo', 'pequeno', 'avisar'], 3, '5c624180-5fca-41fd-a5a0-a6e724f45d96');

-- CATEGORIA 11: OBRAS - GRANDES (10 FAQs: 231-240)
INSERT INTO public.faqs (question, answer, category, tags, keywords, priority, condominio_id) VALUES
('Reforma completa precisa de quê?', 'Projeto, responsável técnico (engenheiro/arquiteto), ART/RRT, alvará (prefeitura), comunicação formal ao síndico.', 'obras_grandes', ARRAY['reforma', 'documentacao', 'legal'], ARRAY['reforma', 'grande', 'projeto', 'alvara'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Posso derrubar parede?', 'Parede interna: SIM (com engenheiro verificando se não é estrutural). Externa ou que afete estrutura: PROIBIDO.', 'obras_grandes', ARRAY['parede', 'estrutura', 'restricao'], ARRAY['parede', 'derrubar', 'quebrar', 'estrutural'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Mudei layout completo, pode?', 'Desde que não afete: estrutura, hidráulica geral, fachada externa. Aprovação de engenheiro necessária.', 'obras_grandes', ARRAY['layout', 'planta', 'reforma'], ARRAY['layout', 'planta', 'mudar', 'completo'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Colocar mezanino é permitido?', 'Depende. Não pode ultrapassar pé-direito ou violar código de obras. Engenheiro deve aprovar estrutura.', 'obras_grandes', ARRAY['mezanino', 'estrutura', 'obra'], ARRAY['mezanino', 'sobrelolja', 'segundo piso'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Obra grande quanto tempo posso demorar?', 'Não há limite legal, mas condomínio pode exigir cronograma. Mais de 6 meses: apresente justificativa ao síndico.', 'obras_grandes', ARRAY['prazo', 'obra', 'tempo'], ARRAY['prazo', 'demora', 'quanto tempo', 'meses'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Posso ampliar minha unidade?', 'NÃO, se invadir área comum ou fachada. SIM, se for vertical (mezanino) dentro do permitido por lei.', 'obras_grandes', ARRAY['ampliacao', 'restricao', 'legal'], ARRAY['ampliar', 'aumentar', 'expansao', 'area'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Obra danificou área comum', 'Você paga o reparo INTEGRALMENTE. Tire fotos antes da obra. Síndico cobrará conserto.', 'obras_grandes', ARRAY['dano', 'area comum', 'responsabilidade'], ARRAY['danificou', 'quebrou', 'dano', 'pagamento'], 1, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Preciso de alvará para reforma?', 'Sim, para reformas estruturais ou que mudem planta. Pequenas reformas (pintura, troca de piso) não.', 'obras_grandes', ARRAY['alvara', 'prefeitura', 'legal'], ARRAY['alvara', 'prefeitura', 'licenca', 'documento'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Instalação de piscina particular', 'Precisa de: projeto estrutural, impermeabilização aprovada por engenheiro, anuência do síndico (verificar carga na laje).', 'obras_grandes', ARRAY['piscina', 'particular', 'obra'], ARRAY['piscina', 'privada', 'instalar', 'obra'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96'),
('Querem construir varanda envidraçada', 'Depende. Se alterar fachada, precisa aprovar em assembleia (2/3 dos condôminos).', 'obras_grandes', ARRAY['varanda', 'fachada', 'assembleia'], ARRAY['varanda', 'vidro', 'sacada', 'envidracada'], 2, '5c624180-5fca-41fd-a5a0-a6e724f45d96');

-- Continua nos próximos comentários devido ao limite de caracteres...
-- As próximas 60 FAQs (241-300) cobrem: Governança-Assembleia, Governança-Síndico, Conflitos

